language: r
os: [linux, osx]
r: release
matrix:
  include:
    - r: devel
    - r: oldrel
cache: packages
latex: false
pandoc: true
fortran: true
git:
  depth: false

before_install:
  # combined with a weekly cron job, bookdown cache would be updated monthly
  - R -e "if (as.integer(substr(Sys.Date(), 9, 10)) < 8 && Sys.getenv('TRAVIS_EVENT_TYPE') == 'cron') unlink(dir(.libPaths()[1], full.names = T), recursive = T)"
  - R --slave -e "source('https://gist.github.com/dongzhuoer/dd332dc13ef06ee4447f69aaacbdcb1a/raw/move-recommended-packages-to-user-library-for-travis.R')"
  - R --slave -e "update.packages(ask = F)"
install:
  - R --slave -e "if (!('devtools' %in% .packages(T))) install.packages('devtools')"
script:
  - R --slave -e "devtools::install_local(getwd())"
  - R --slave -e "devtools::update_packages(c('testthat', 'roxygen2')); devtools::load_all(); if (dir.exists('tests/testthat')) {devtools::test(); testthat::test_dir('tests/testthat/', reporter = 'fail')}"

notifications:
  email: false
