import: dongzhuoer/minir:.travis.yml
# `before_script` always overwrites existing, `deep_merge_prepend` just don't work as excepted, 
#   "concatenates sequences (arrays) by either appending or prepending to the sequence in the importing config"
before_install: apt="pandoc pandoc-citeproc"  
