---
title: "Introduction to zhuoerdown"
author: "Zhuoer Dong"
date: "`r Sys.Date()`"
output: prettydoc::html_pretty
vignette: >
  %\VignetteIndexEntry{Introduction to zhuoerdown}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```



# Innovation

There are so many good bookdown books freely available online, with source code open. However, the network is so slow (especially in Nankai University), and I want to customize the appearance. To solve the first problem, I regularly fetch source code and build the book myself ^[To be precise, I build the book on Travis and `git clone` the output, with the bonus that others can also get the output (if they share similar preference with me).]. And the second one can be solved by overwriting `_output.yml`. Here comes this package, which glues the two solution together, i.e., overwrite (patially) `_output.yml` without editing the original file. I'm sorry if you find the package clumsy to use, since it's tailored for my personal usage,



# Usage

`make_gitbook()` overwrites original `_output.yml` by Zhuoer's favirote [_output.yml](https://github.com/dongzhuoer/zhuoerdown/blob/master/inst/_output.yml) (with [bookdown.css](https://github.com/dongzhuoer/zhuoerdown/blob/master/inst/bookdown.css)), then by user provided `_output.yml` (`output_format_file` parameter).

It also add several links in TOC:

- `url` to respect the author's copyright
- `download_link` to share the output with others
